### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kovalandrew** [tunetab/TheBestProject#1]
- [x] Убрать остатки от спотифая
- [x] Проверить структуру папок - файлы некорректно по группам распределены. Например PlayerViewController лежит не в папке ViewControllers, а в корне проекта (именно на диске, не в проекте)
- [x] @IBOutlet-ы лучше делать приватными. Это нужно для того, чтобы не было возможности снаружи как-то влиять на элемены UI у контроллера. Правильнее использовать методы настройки, чтобы конфигурация была завёрнута внутри самого контроллера
- ProfileViewController
   - [x] Для чего тут поле приватное reuseIdentifier ? Оно нигде не используется. 
   - [x] Публичные поля надо делать приватными. paylists, datasource, snapshot - это внутренние вещи самого контроллера. О них не должны знать снаружи.
   - [x] Будет лучше и более читабельно viewDidLoad разбить на отдельные методы. Например вот createDataSource есть отдельный. Вот также можно сделать методы setupCollectionView и там ему уже настроить делегата и лейаут, а в didLoad просто вызвать его. Также и с imageView
   - [x] `let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "PlaylistCell", for: indexPath) as! PlaylistCollectionViewCell` - не надо хардкодить идентефикаторы ячеек. Можно в классе самой ячейки сделать статическое свойство reuseIdentifier. Тогда у тебя всегда каждая ячейка будет свой идентификатор знать. Также лучше убрать форскаст. Либо через guard let, либо через if let развернуть.
   - [x] `@IBSegueAction func openPlaylist` так не стоит делать. Тут получается очень сильная связность. И на конкретную ячейку, и на конкретные данные. Правильнее будет воспользоваться, например, методом делегата коллекции didSelectCell atIndexPath. Так у тебя сработает событие о том, что какую то ячейку коллекции нажали. По индеску получишь плейлист и сделаешь переход

**Comment by tunetab** [comment]
Yep
